version: '3.8'

services:
  backend:
    build:
      context: ./backend/BackendPFE
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smarttechdb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: smarttechdb
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend/smarttech_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
    - REACT_APP_BACKEND_URL=http://backend:9000

